CREATE TABLE IF NOT EXISTS users(
    id VARCHAR (36) PRIMARY KEY NOT NULL DEFAULT (UUID()),
    first_name VARCHAR (50) NOT NULL,
    last_name VARCHAR (50) NOT NULL,
    age INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);